# Generated by Django 3.2.19 on 2023-05-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discouted_price',
            new_name='discounted_price',
        ),
    ]
