# Generated by Django 3.2.19 on 2023-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230521_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titre',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
